window.ALERT_INDEX = ({
  'cpu-usage': { direction: 'high_is_bad', warn: 85, crit: 95 },
  'cpu-temp': { direction: 'high_is_bad', warn: 60, crit: 92 },
  'gpu-usage': { direction: 'high_is_bad', warn: 92, crit: 96 },
  'gpu-temp': { direction: 'high_is_bad', warn: 65, crit: 83 },
  'gpu-vramDedGB': { direction: 'saturation', warn: 90, crit: 95, capacity: 6.0 },
  'gpu-vramTotGB': { direction: 'saturation', warn: 80, crit: 90, capacity: 14.0 },
  'net-upKbps': { direction: 'saturation', warn: 85, crit: 95, capacity: 100000 },
  'net-downKbps': { direction: 'saturation', warn: 85, crit: 95, capacity: 100000 },
  'net-pingMs': { direction: 'high_is_bad', warn: 20, crit: 30 },
  'disk-usagePct': { direction: 'high_is_bad', warn: 80, crit: 95 },
  'disk-latency': { direction: 'high_is_bad', warn: 40, crit: 50 },
  'disk-freePct': { direction: 'low_is_bad', warn: 20, crit: 10 },
  'disk-readKBps': { direction: 'saturation', warn: 85, crit: 95, capacity: 120000 },
  'disk-writeKBps': { direction: 'saturation', warn: 85, crit: 95, capacity: 120000 },
  // Porcentaje de actividad de lectura/escritura (0..100)
  'disk-readPct': { direction: 'saturation', warn: 85, crit: 95, capacity: 100 },
  'disk-writePct': { direction: 'saturation', warn: 85, crit: 95, capacity: 100 },
  // Claves normalizadas para discos específicos (disk-<idx>-<metric>)
  'disk-0-latency': { direction: 'high_is_bad', warn: 40, crit: 50 },
  'disk-0-readKBps': { direction: 'saturation', warn: 85, crit: 95, capacity: 520000 },
  'disk-0-writeKBps': { direction: 'saturation', warn: 85, crit: 95, capacity: 350000 },
  'disk-0-readPct': { direction: 'saturation', warn: 85, crit: 95, capacity: 100 },
  'disk-0-writePct': { direction: 'saturation', warn: 85, crit: 95, capacity: 100 },
  'disk-1-latency': { direction: 'high_is_bad', warn: 40, crit: 50 },
  'disk-1-readKBps': { direction: 'saturation', warn: 85, crit: 95, capacity: 190000 },
  'disk-1-writeKBps': { direction: 'saturation', warn: 85, crit: 95, capacity: 190000 },
  'disk-1-readPct': { direction: 'saturation', warn: 85, crit: 95, capacity: 100 },
  'disk-1-writePct': { direction: 'saturation', warn: 85, crit: 95, capacity: 100 },
  'mem-physGB': { direction: 'saturation', warn: 85, crit: 90, capacity: 16.0 },
  'mem-virtGB': { direction: 'saturation', warn: 85, crit: 90, capacity: 35.1 },
});